
services:
  - type: web
    name: rdrive-file-upload-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: APP_NAME
        value: rdrive-file-upload-api
      - key: UPLOAD_DIR
        value: uploads
